# Generated by Django 3.2.5 on 2023-01-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500, null=True)),
                ('banner_pic', models.ImageField(upload_to='course_banner_pics')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('length', models.IntegerField()),
                ('resources', models.FileField(upload_to='course_resources')),
                ('price', models.IntegerField()),
                ('discount_percentage', models.IntegerField(default=0)),
                ('active_status', models.BooleanField(default=False)),
            ],
        ),
    ]
