# Generated by Django 3.2.5 on 2023-01-31 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_CourseTransaction', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
